import { Paciente } from '../../types';


export const PACIENTES_MOCK: Paciente[] = [
    {
        id_paciente: 1,
        rut: '19.876.543-K',
        nombre: 'Carlos',
        apellido: 'Mendoza',
        fecha_nacimiento: '2022-03-15',
        sexo_biologico: 'Masculino',
        identidad_genero: 'Masculino',
        nacionalidad: 'Chilena',
        direccion: 'Calle 5, #123',
        sector: 'Centro',
        comuna: 'La Granja',
        nhc: 'HC-2022-001',
        prevision: 'FONASA',
        fecha_inscripcion: '2022-03-15',
        activo: true,
        es_sename: false,
        es_naneas_prematuro: false,
        es_poblacion_trans: false,
        es_migrante: false,
        id_tutor_principal: 1,
        tutor: {
            id_tutor: 1,
            rut: '12.345.678-K',
            nombre: 'María',
            apellido: 'González',
            telefono: '+56912345678',
            parentesco: 'Madre',
            correo: 'maria@example.com',
            direccion: 'Calle 5, #123',
            sector: 'Centro',
            comuna: 'La Granja',
        },
    },
    {
        id_paciente: 2,
        rut: '19.654.321-J',
        nombre: 'Sofía',
        apellido: 'López',
        fecha_nacimiento: '2023-07-22',
        sexo_biologico: 'Femenino',
        identidad_genero: 'Femenino',
        nacionalidad: 'Chilena',
        direccion: 'Avenida Principal, #456',
        sector: 'Oriente',
        comuna: 'Ñuñoa',
        nhc: 'HC-2023-002',
        prevision: 'ISAPRE',
        fecha_inscripcion: '2023-07-22',
        activo: true,
        es_sename: false,
        es_naneas_prematuro: true,
        es_poblacion_trans: false,
        es_migrante: false,
        id_tutor_principal: 2,
        tutor: {
            id_tutor: 2,
            rut: '11.222.333-K',
            nombre: 'Roberto',
            apellido: 'López',
            telefono: '+56987654321',
            parentesco: 'Padre',
            correo: 'roberto@example.com',
            direccion: 'Avenida Principal, #456',
            sector: 'Oriente',
            comuna: 'Ñuñoa',
        },
    },
    {
        id_paciente: 3,
        rut: '19.555.666-L',
        nombre: 'Lucas',
        apellido: 'Sánchez',
        fecha_nacimiento: '2024-01-10',
        sexo_biologico: 'Masculino',
        identidad_genero: 'Masculino',
        nacionalidad: 'Chilena',
        direccion: 'Pasaje 10, #789',
        sector: 'Poniente',
        comuna: 'Maipú',
        nhc: 'HC-2024-003',
        prevision: 'FONASA',
        fecha_inscripcion: '2024-01-10',
        activo: true,
        es_sename: false,
        es_naneas_prematuro: false,
        es_poblacion_trans: false,
        es_migrante: true,
        id_tutor_principal: 3,
        tutor: {
            id_tutor: 3,
            rut: '13.456.789-2',
            nombre: 'Ana',
            apellido: 'Sánchez',
            telefono: '+56911223344',
            parentesco: 'Madre',
            correo: 'ana@example.com',
            direccion: 'Pasaje 10, #789',
            sector: 'Poniente',
            comuna: 'Maipú',
        },
    },
];
