version: '3.8'

services:
  # Instancia 1: Frontend (Ubuntu)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # Instancia 2: Backend (Ubuntu)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=cesfam_db
      - DB_PORT=5432
    depends_on:
      - database

  
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cesfam_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: