# Usar la imagen oficial de PostgreSQL
FROM postgres:15-alpine

# Configurar variables de entorno (Usuario, Contraseña y Nombre de la BD)
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=admin123
ENV POSTGRES_DB=cesfam_db

# Copiar el script de inicialización
# Docker ejecuta automáticamente cualquier .sql que esté en esta carpeta al iniciar por primera vez
COPY init.sql /docker-entrypoint-initdb.d/

# Exponer el puerto por defecto de PostgreSQL
EXPOSE 5433