-- Este archivo se ejecuta automáticamente por la imagen oficial de Postgres
-- la primera vez que el volumen de datos está vacío.
--
-- El schema real de la aplicación es gestionado por Prisma (ver backend/prisma/migrations/),
-- no por este archivo. Se deja vacío intencionalmente para que Prisma sea la única
-- fuente de verdad del schema.